services:
  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - fia_hackathon_network
  postgres:
    image: postgres:${DB_VERSION}
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/${DB_VERSION}/docker
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    networks:
      - fia_hackathon_network
    build:
      context: .
      dockerfile: apps/mlService/mlService/Dockerfile.pg
      args:
        DB_VERSION: ${DB_VERSION}
  mlService:
    user: '${UID}:${GID}'
    image: fia-hackathon-mlservice:dev
    build:
      context: .
      dockerfile: ./apps/mlService/Dockerfile.dev
    env_file: .mlService.env
    environment:
      - UV_LINK_MODE=copy
      - UV_PROJECT_ENVIRONMENT=/tmp/.venv
    volumes:
      - ./apps/mlService:/app:rw
      - ml_venv:/app/.venv
      - /app/apps/mlService/.egg-info
      - ${HF_CACHE}:/usr/fia # so selfish, swedka. So selfish
      - ./laws_database.json:/data/laws_database.json:ro
      - ml:/usr/fia
      - ./categories.json:/data/categories.json:ro
    networks:
      - fia_hackathon_network
    depends_on:
      - redis
  backend:
    user: '${UID}:${GID}'
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile.dev
    env_file: .backend.env
    ports:
      - 4000:4000
      - 3001:3001
    volumes:
      - ./apps/backend:/app/apps/backend:rw
      - deps_backend:/app/apps/backend/node_modules
    networks:
      - fia_hackathon_network

networks:
  fia_hackathon_network:
volumes:
  deps_backend:
  postgres_data:
  ml:
  ml_venv:
