services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - "3000:3000"

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    ports:
      - "4200:4200"

  mlservice:
    build:
      context: .
      dockerfile: apps/MlService/Dockerfile
    ports:
      - "8000:8000"
