FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY ./apps/frontend/public ./apps/frontend/public
COPY --chown=nextjs:nodejs ./dist/apps/frontend/.next/standalone ./
COPY --chown=nextjs:nodejs ./dist/apps/frontend/.next/static ./dist/apps/frontend/.next/static

USER nextjs

EXPOSE 4200
ENV PORT=4200
ENV HOSTNAME="0.0.0.0"

CMD ["node", "apps/frontend/server.js"]