import './global.css';
import { DM_Sans, Noto_Sans, Oswald } from 'next/font/google';
import localFont from 'next/font/local';
import { cn } from '@/lib/utils';
import MainHeader from '@/components/blocks/MainHeader';

const notoSansHeading = Noto_Sans({
  subsets: ['latin'],
  variable: '--font-heading',
});

const font1 = localFont({
  src: '../../public/1.ttf',
  variable: '--font-1',
});

const oswald = Oswald({ variable: '--font-logo' });

const dmSans = DM_Sans({ subsets: ['latin'], variable: '--font-sans' });

export const metadata = {
  title: 'Welcome to frontend',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={cn(
        'font-sans',
        dmSans.variable,
        notoSansHeading.variable,
        'dark',
      )}
    >
      <body>
        <MainHeader />
        {children}
      </body>
    </html>
  );
}
