import './global.css';
import { Golos_Text, Noto_Sans, Oswald } from 'next/font/google';
import { cn } from '@/lib/utils';
import MainHeader from '@/components/blocks/MainHeader';
import MainFooter from '@/components/blocks/MainFooter';
import GeolocationAccessModal from '@/components/widget/GeolocationAccessModal';
import InputStreetModal from '@/components/widget/InputStreetModal';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';

const notoSansHeading = Noto_Sans({
  subsets: ['latin', 'cyrillic'],
  variable: '--font-heading',
});

//@ts-expect-error ddd
const oswald = Oswald({ variable: '--font-logo' });

const dmSans = Golos_Text({
  subsets: ['latin', 'cyrillic'],
  variable: '--font-sans',
});

export const metadata = {
  title: 'Welcome to frontend',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const queryClient = new QueryClient();

  return (
    <html
      lang="en"
      className={cn(
        'font-sans',
        dmSans.variable,
        notoSansHeading.variable,
        'dark',
      )}
    >
      <QueryClientProvider client={queryClient}>
        <body>
          <MainHeader />
          <div className="fixed w-full h-full top-0 left-0 z-[999] pointer-events-none flex justify-center items-center">
            <GeolocationAccessModal />
            <InputStreetModal />
          </div>
          {children}
          <MainFooter />
        </body>
      </QueryClientProvider>
    </html>
  );
}
