FROM node:22-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production

COPY ./apps/backend/package.json .
RUN npm i --omit=dev

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nestjs

COPY --chown=nestjs:nodejs ./apps/backend/dist ./dist

RUN mkdir /usr/fia/ && chown -R nestjs:nodejs /usr/fia

VOLUME [ "/usr/fia" ]

USER nestjs

CMD ["node", "dist/main.js"]