FROM node:22-alpine AS runner

WORKDIR /app

COPY ./apps/backend/package.json ./apps/backend/
RUN cd apps/backend && npm install

COPY ./apps/backend/ ./apps/backend/

WORKDIR /app/apps/backend

ENV CHOKIDAR_USEPOLLING=true
ENV WATCHPACK_POLLING=true

# Фіксуємо змінні оточення окремо
ENV NODE_OPTIONS="-r tsconfig-paths/register"

RUN mkdir /usr/fia

CMD ["npx", "nodemon", "--legacy-watch", "--watch", "src", "-e", "ts", "--exec", "npx nest start"]
