FROM node:22-alpine AS runner

RUN apk update && apk add --no-cache \
    chromium \
    nss \
    freetype \
    harfbuzz \
    ca-certificates \
    ttf-freefont

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium

WORKDIR /app

COPY ./apps/backend/package.json ./apps/backend/
RUN cd apps/backend && npm install

COPY ./apps/backend/ ./apps/backend/

WORKDIR /app/apps/backend

ENV CHOKIDAR_USEPOLLING=true
ENV WATCHPACK_POLLING=true

# Фіксуємо змінні оточення окремо
ENV NODE_OPTIONS="-r tsconfig-paths/register"

RUN mkdir /usr/fia

CMD ["npx", "nodemon", "--legacy-watch", "--watch", "src", "-e", "ts", "--exec", "npx nest start"]
