FROM python:3.14-slim AS development
WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV UV_NO_CACHE=1 

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

COPY apps/mlService/pyproject.toml ./apps/mlService/
COPY apps/mlService/uv.lock* ./apps/mlService

RUN uv pip install --system -r apps/mlService/pyproject.toml
COPY ./apps/mlService/ ./apps/mlService/

RUN uv pip install --system --editable ./apps/mlService

CMD ["python", "-m", "mlService"]