FROM python:3.12-slim

WORKDIR /app

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

COPY apps/mlService/pyproject.toml ./apps/mlService/
COPY apps/mlService/uv.lock* ./apps/mlService/

COPY ./apps/mlService/ ./apps/mlService/

WORKDIR /app/apps/mlService

RUN uv sync

WORKDIR /app

RUN mkdir /usr/fia
ENV HF_CACHE=/usr/fia
ENV HF_HOME=/usr/fia
ENV SENTENCE_TRANSFORMERS_HOME=/usr/fia
ENV TOKENIZERS_PARALLELISM=false

CMD ["uv", "run", "python", "-m", "mlService"]