FROM python:3.11-alpine AS runner
WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

RUN addgroup --system --gid 1001 pythonjs && \
    adduser --system --uid 1001 pythonapp

COPY ./apps/mlService/dist ./dist_packages

RUN uv pip install --system --no-cache ./dist_packages/*.whl
RUN rm -rf ./dist_packages

USER pythonapp

CMD ["python", "-m", "mlService"]