name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read
  packages: write

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - run: npm ci
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - run: npx nx start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e"

      - run: npx nx record -- npx nx format:check --base="remotes/origin/main"
      - run: npx nx record -- npx nx format:check --base="remotes/origin/main"

      - run: npx nx run-many -t lint test typecheck e2e --exclude=mlService

      - run: npx nx run-many -t lint test -p mlService --no-cloud

      - run: npx nx run-many -t build-container --no-cloud

      - name: Log in to GHCR
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker Images
        if: github.ref == 'refs/heads/main'
        run: npx nx run-many -t container-push

      - run: npx nx fix-ci
        if: always()
